#pragma once

#include "Kernel/Logger.h"

#define LOGGER_HTTP_ERROR( ... ) LOGGER_VERBOSE_LEVEL( "http", Mengine::LM_ERROR, Mengine::LFILTER_HTTP, Mengine::LCOLOR_RED, MENGINE_CODE_FILE, MENGINE_CODE_LINE, MENGINE_CODE_FUNCTION, Mengine::LFLAG_FULL )( __VA_ARGS__ )
#define LOGGER_HTTP_MESSAGE_RELEASE( ... ) LOGGER_VERBOSE_LEVEL( "http", Mengine::LM_MESSAGE_RELEASE, Mengine::LFILTER_HTTP, Mengine::LCOLOR_GREEN, MENGINE_CODE_FILE, MENGINE_CODE_LINE, MENGINE_CODE_FUNCTION, Mengine::LFLAG_SHORT )( __VA_ARGS__ )
#define LOGGER_HTTP_MESSAGE( ... ) LOGGER_VERBOSE_LEVEL( "http", Mengine::LM_MESSAGE, Mengine::LFILTER_HTTP, Mengine::LCOLOR_GREEN, MENGINE_CODE_FILE, MENGINE_CODE_LINE, MENGINE_CODE_FUNCTION, Mengine::LFLAG_SHORT )( __VA_ARGS__ )
#define LOGGER_HTTP_STATISTIC( ... ) LOGGER_VERBOSE_LEVEL( "http", Mengine::LM_INFO, Mengine::LFILTER_HTTP, Mengine::LCOLOR_GREEN, MENGINE_CODE_FILE, MENGINE_CODE_LINE, MENGINE_CODE_FUNCTION, Mengine::LFLAG_SHORT )( __VA_ARGS__ )
#define LOGGER_HTTP_INFO( ... ) LOGGER_VERBOSE_LEVEL( "http", Mengine::LM_INFO, Mengine::LFILTER_HTTP, Mengine::LCOLOR_GREEN, MENGINE_CODE_FILE, MENGINE_CODE_LINE, MENGINE_CODE_FUNCTION, Mengine::LFLAG_FULL )( __VA_ARGS__ )
