#pragma once

#include "Interface/StatisticServiceInterface.h"

#include "Kernel/ConstStringHelper.h"

#if MENGINE_STATISTIC == 1
#   define STATISTIC_ADD_INTEGER(NAME, VALUE)\
        STATISTIC_SERVICE()->addStatisticInteger(STRINGIZE_STRING_LOCAL(NAME), VALUE)
#   define STATISTIC_ADD_DOUBLE(NAME, VALUE)\
        STATISTIC_SERVICE()->addStatisticDouble(STRINGIZE_STRING_LOCAL(NAME), VALUE)
#   define STATISTIC_HAS_INTEGER(NAME)\
        STATISTIC_SERVICE()->hasStatisticInteger(STRINGIZE_STRING_LOCAL(NAME))
#   define STATISTIC_HAS_DOUBLE(NAME)\
        STATISTIC_SERVICE()->hasStatisticDouble(STRINGIZE_STRING_LOCAL(NAME))
#   define STATISTIC_GET_INTEGER(NAME)\
        STATISTIC_SERVICE()->getStatisticInteger(STRINGIZE_STRING_LOCAL(NAME))
#   define STATISTIC_GET_DOUBLE(NAME)\
        STATISTIC_SERVICE()->getStatisticDouble(STRINGIZE_STRING_LOCAL(NAME))
#   define STATISTIC_RESET_INTEGER(NAME)\
        STATISTIC_SERVICE()->resetStatisticInteger(STRINGIZE_STRING_LOCAL(NAME))
#   define STATISTIC_RESET_DOUBLE(NAME)\
        STATISTIC_SERVICE()->resetStatisticDouble(STRINGIZE_STRING_LOCAL(NAME))
#else
#   define STATISTIC_ADD_INTEGER(NAME, VALUE)
#   define STATISTIC_ADD_DOUBLE(NAME, VALUE)
#   define STATISTIC_HAS_INTEGER(NAME)
#   define STATISTIC_HAS_DOUBLE(NAME)
#   define STATISTIC_GET_INTEGER(NAME)
#   define STATISTIC_GET_DOUBLE(NAME)
#   define STATISTIC_RESET_INTEGER(NAME)
#   define STATISTIC_RESET_DOUBLE(NAME)
#endif