#pragma once

#include "Interface/StatisticServiceInterface.h"

#include "Kernel/ConstStringHelper.h"

#ifdef MENGINE_STATISTIC_ENABLE
#   define STATISTIC_ADD_INTEGER(NAME, VALUE) (SERVICE_IS_AVAILABLE(StatisticServiceInterface) == true ? STATISTIC_SERVICE()->addStatisticInteger(STRINGIZE_STRING_LOCAL(NAME), VALUE) : MENGINE_NOP)
#   define STATISTIC_HAS_INTEGER(NAME) (SERVICE_IS_AVAILABLE(StatisticServiceInterface) == true ? STATISTIC_SERVICE()->hasStatisticInteger(STRINGIZE_STRING_LOCAL(NAME)) : false)
#   define STATISTIC_GET_INTEGER(NAME) (SERVICE_IS_AVAILABLE(StatisticServiceInterface) == true ? STATISTIC_SERVICE()->getStatisticInteger(STRINGIZE_STRING_LOCAL(NAME)) : 0LL)
#   define STATISTIC_RESET_INTEGER(NAME) (SERVICE_IS_AVAILABLE(StatisticServiceInterface) == true ? STATISTIC_SERVICE()->resetStatisticInteger(STRINGIZE_STRING_LOCAL(NAME)) : MENGINE_NOP)

#   define STATISTIC_ADD_DOUBLE(NAME, VALUE) (SERVICE_IS_AVAILABLE(StatisticServiceInterface) == true ? STATISTIC_SERVICE()->addStatisticDouble(STRINGIZE_STRING_LOCAL(NAME), VALUE) : MENGINE_NOP)
#   define STATISTIC_HAS_DOUBLE(NAME) (SERVICE_IS_AVAILABLE(StatisticServiceInterface) == true ? STATISTIC_SERVICE()->hasStatisticDouble(STRINGIZE_STRING_LOCAL(NAME)) : false)
#   define STATISTIC_GET_DOUBLE(NAME) (SERVICE_IS_AVAILABLE(StatisticServiceInterface) == true ? STATISTIC_SERVICE()->getStatisticDouble(STRINGIZE_STRING_LOCAL(NAME)) : 0.0)
#   define STATISTIC_RESET_DOUBLE(NAME) (SERVICE_IS_AVAILABLE(StatisticServiceInterface) == true ? STATISTIC_SERVICE()->resetStatisticDouble(STRINGIZE_STRING_LOCAL(NAME)) : MENGINE_NOP)

#   define STATISTIC_SET_CONSTSTRING(NAME, VALUE) (SERVICE_IS_AVAILABLE(StatisticServiceInterface) == true ? STATISTIC_SERVICE()->setStatisticConstString(STRINGIZE_STRING_LOCAL(NAME), VALUE) : MENGINE_NOP)
#   define STATISTIC_HAS_CONSTSTRING(NAME) (SERVICE_IS_AVAILABLE(StatisticServiceInterface) == true ? STATISTIC_SERVICE()->hasStatisticConstString(STRINGIZE_STRING_LOCAL(NAME)) : false)
#   define STATISTIC_GET_CONSTSTRING(NAME) (SERVICE_IS_AVAILABLE(StatisticServiceInterface) == true ? STATISTIC_SERVICE()->getStatisticConstString(STRINGIZE_STRING_LOCAL(NAME)) : ConstString::none())
#   define STATISTIC_RESET_CONSTSTRING(NAME) (SERVICE_IS_AVAILABLE(StatisticServiceInterface) == true ? STATISTIC_SERVICE()->resetStatisticConstString(STRINGIZE_STRING_LOCAL(NAME)) : MENGINE_NOP)
#else
#   define STATISTIC_ADD_INTEGER(NAME, VALUE)
#   define STATISTIC_HAS_INTEGER(NAME)
#   define STATISTIC_GET_INTEGER(NAME) (0LL)
#   define STATISTIC_RESET_INTEGER(NAME)

#   define STATISTIC_ADD_DOUBLE(NAME, VALUE)
#   define STATISTIC_HAS_DOUBLE(NAME)
#   define STATISTIC_GET_DOUBLE(NAME) (0.0)
#   define STATISTIC_RESET_DOUBLE(NAME)

#   define STATISTIC_SET_CONSTSTRING(NAME, VALUE)
#   define STATISTIC_HAS_CONSTSTRING(NAME)
#   define STATISTIC_GET_CONSTSTRING(NAME) (ConstString::none())
#   define STATISTIC_RESET_CONSTSTRING(NAME)
#endif