#pragma once

#define MENGINE_THREAD_PRIORITY_LOWEST (-2)
#define MENGINE_THREAD_PRIORITY_BELOW_NORMAL (-1)
#define MENGINE_THREAD_PRIORITY_NORMAL (0)
#define MENGINE_THREAD_PRIORITY_ABOVE_NORMAL (1)
#define MENGINE_THREAD_PRIORITY_HIGHEST (2)
#define MENGINE_THREAD_PRIORITY_TIME_CRITICAL (3)
