set(EXTERNAL_PROJECT_NAME curl)

set(EXTERNAL_LIBRARY_FILE_NAME curl)

if(MENGINE_PLATFORM_XCODE)
    set(CURL_USE_OPENSSL OFF)    
endif()

if(MENGINE_PLATFORM_ANDROID)
    set(CURL_USE_OPENSSL OFF)
endif()
    
if(MENGINE_PLATFORM_WIN32)
    set(CURL_USE_WINSSL ON)
endif()

if(MENGINE_PLATFORM_IOS)
    set(CURL_ENABLE_THREADED_RESOLVER OFF)
    set(CURL_USE_LIBSSH2 OFF)
    set(CURL_USE_DARWINSSL ON)
endif()

ExternalProject_Add(${EXTERNAL_PROJECT_NAME}_download PREFIX ${EXTERNAL_PROJECT_NAME}
        SOURCE_DIR ${DOWNLOADS_DIR}/${EXTERNAL_PROJECT_NAME}
        
        GIT_REPOSITORY https://github.com/curl/curl.git
        GIT_TAG "7.61.1"
        GIT_PROGRESS TRUE

        UPDATE_COMMAND ""

        CMAKE_ARGS
            -DCMAKE_INSTALL_PREFIX=${THIRDPARTY_DIR}/${EXTERNAL_PROJECT_NAME}
            -DBUILD_SHARED_LIBS=OFF
            -DLIBTYPE=STATIC
            -DBUILD_CURL_EXE=OFF
            -DBUILD_TESTING=OFF
            -DENABLE_MANUAL=OFF
            -DCURL_STATICLIB=ON
            -DHTTP_ONLY=OFF
            -DCURL_DISABLE_FTP=ON
            -DCURL_DISABLE_LDAP=ON
            -DCURL_DISABLE_LDAPS=ON
            -DCURL_DISABLE_TELNET=ON
            -DCURL_DISABLE_DICT=ON
            -DCURL_DISABLE_FILE=ON
            -DCURL_DISABLE_TFTP=ON
            -DCURL_DISABLE_RTSP=ON
            -DCURL_DISABLE_PROXY=ON
            -DCURL_DISABLE_POP3=ON
            -DCURL_DISABLE_IMAP=ON
            -DCURL_DISABLE_SMTP=ON
            -DCURL_DISABLE_GOPHER=ON
            -DCURL_DISABLE_COOKIES=ON
            -DCURL_DISABLE_CRYPTO_AUTH=ON
            -DCMAKE_USE_LIBSSH2=OFF
            -DCURL_CA_PATH="none"
            -DCMAKE_USE_OPENSSL=${CURL_USE_OPENSSL}
            -DCMAKE_USE_WINSSL=${CURL_USE_WINSSL}
            -DENABLE_THREADED_RESOLVER=${CURL_ENABLE_THREADED_RESOLVER}
            -DCMAKE_USE_LIBSSH2=${CURL_USE_LIBSSH2}
            -DCMAKE_USE_DARWINSSL=${CURL_USE_DARWINSSL}
)

ExternalProject_Get_Property(${EXTERNAL_PROJECT_NAME}_download INSTALL_DIR)
set(EXTERNAL_PROJECT_INCLUDE_DIR ${INSTALL_DIR}/include)
set(EXTERNAL_PROJECT_LIBRARY_DIR ${INSTALL_DIR}/lib)

add_library(${EXTERNAL_PROJECT_NAME} STATIC IMPORTED)

set_target_properties(${EXTERNAL_PROJECT_NAME} PROPERTIES IMPORTED_LOCATION ${EXTERNAL_PROJECT_LIBRARY_DIR}/${CMAKE_STATIC_LIBRARY_PREFIX}${EXTERNAL_LIBRARY_FILE_NAME}${CMAKE_STATIC_LIBRARY_SUFFIX})

