set(EXTERNAL_PROJECT_NAME libpng)

set(EXTERNAL_LIBRARY_FILE_NAME png)

ExternalProject_Add(${EXTERNAL_PROJECT_NAME}_download PREFIX ${EXTERNAL_PROJECT_NAME}
        SOURCE_DIR ${DOWNLOADS_DIR}/${EXTERNAL_PROJECT_NAME}
        
        GIT_REPOSITORY https://github.com/glennrp/libpng.git
        GIT_TAG "v1.6.35"
        GIT_PROGRESS TRUE

        UPDATE_COMMAND ${CMAKE_COMMAND} -E copy
			${CMAKE_DEPENDENCIES_DIR}/${EXTERNAL_PROJECT_NAME}/pnglibconf.h
			${DOWNLOADS_DIR}/${EXTERNAL_PROJECT_NAME}/pnglibconf.h

        CMAKE_ARGS
            -DCMAKE_INSTALL_PREFIX=${THIRDPARTY_DIR}/${EXTERNAL_PROJECT_NAME}
            -DBUILD_SHARED_LIBS=OFF
            -DLIBTYPE=STATIC
            -DPNG_SHARED=ON
            -DPNG_STATIC=ON
            -DPNG_TESTS=ON
            -DPNG_FRAMEWORK=ON
            -DPNG_DEBUG=ON
            -DPNGARG=ON
            -DPNG_HARDWARE_OPTIMIZATIONS=OFF
            -DZLIB_LIBRARY=${THIRDPARTY_DIR}/zlib
            -DZLIB_INCLUDE_DIR=${THIRDPARTY_DIR}/zlib
)

ExternalProject_Get_Property(${EXTERNAL_PROJECT_NAME}_download INSTALL_DIR)
set(EXTERNAL_PROJECT_INCLUDE_DIR ${INSTALL_DIR}/include)
set(EXTERNAL_PROJECT_LIBRARY_DIR ${INSTALL_DIR}/lib)

add_library(${EXTERNAL_PROJECT_NAME} STATIC IMPORTED)

set_target_properties(${EXTERNAL_PROJECT_NAME} PROPERTIES IMPORTED_LOCATION ${EXTERNAL_PROJECT_LIBRARY_DIR}/${CMAKE_STATIC_LIBRARY_PREFIX}${EXTERNAL_LIBRARY_FILE_NAME}${CMAKE_STATIC_LIBRARY_SUFFIX})

add_dependencies(${EXTERNAL_PROJECT_NAME}_download
    zlib_download
    stdex_download
    )