set(EXTERNAL_PROJECT_NAME metabuf)

set(EXTERNAL_LIBRARY_FILE_NAME metabuf)

if(WIN32)
    set(METABUF_XML2METABUF ON)
else()
    set(METABUF_XML2METABUF OFF)
endif()

ExternalProject_Add(${EXTERNAL_PROJECT_NAME}_download PREFIX ${EXTERNAL_PROJECT_NAME}
        SOURCE_DIR ${DOWNLOADS_DIR}/${EXTERNAL_PROJECT_NAME}        

        GIT_REPOSITORY https://github.com/irov/metabuf.git
        GIT_PROGRESS TRUE
        
        UPDATE_COMMAND ${CMAKE_COMMAND} -E copy
			${CMAKE_DEPENDENCIES_DIR}/${EXTERNAL_PROJECT_NAME}/Metaconfig.hpp
			${DOWNLOADS_DIR}/${EXTERNAL_PROJECT_NAME}/metabuf/MyMetaconfig.hpp

        CMAKE_ARGS
            -DCMAKE_INSTALL_PREFIX=${THIRDPARTY_DIR}/${EXTERNAL_PROJECT_NAME}
            -DPROJECT_CONFIGURE_DIR=${CMAKE_DEPENDENCIES_DIR}/${EXTERNAL_PROJECT_NAME}
            -DTHIRDPARTY_DIR=${THIRDPARTY_DIR}
            -DBUILD_SHARED_LIBS=OFF
            -DMETABUF_EXTERNAL_BUILD=ON
            -DMETABUF_METAGEN=OFF
            -DMETABUF_XML2METABUF=${METABUF_XML2METABUF}
            -DMETABUF_PUGIXML_EXTERNAL=ON
            -DMETABUF_PUGIXML_INCLUDE_DIR=${THIRDPARTY_DIR}/pugixml/include
            -DMETABUF_PUGIXML_LIBRARY_NAME=${THIRDPARTY_DIR}/pugixml/lib
            -DMETABUF_INSTALL=ON
            -DMETABUF_CONFIG="MyMetaconfig.hpp"
)

ExternalProject_Get_Property(${EXTERNAL_PROJECT_NAME}_download INSTALL_DIR)
set(EXTERNAL_PROJECT_INCLUDE_DIR ${INSTALL_DIR}/include)
set(EXTERNAL_PROJECT_LIBRARY_DIR ${INSTALL_DIR}/lib)

add_library(${EXTERNAL_PROJECT_NAME} STATIC IMPORTED)

set_target_properties(${EXTERNAL_PROJECT_NAME} PROPERTIES IMPORTED_LOCATION ${EXTERNAL_PROJECT_LIBRARY_DIR}/${CMAKE_STATIC_LIBRARY_PREFIX}${EXTERNAL_LIBRARY_FILE_NAME}${CMAKE_STATIC_LIBRARY_SUFFIX})

add_dependencies(${EXTERNAL_PROJECT_NAME}_download 
    pugixml_download
    stdex_download
    )
