set(EXTERNAL_PROJECT_NAME pugixml)

set(EXTERNAL_LIBRARY_FILE_NAME pugixml)

ExternalProject_Add(${EXTERNAL_PROJECT_NAME}_download PREFIX ${EXTERNAL_PROJECT_NAME}
        SOURCE_DIR ${DOWNLOADS_DIR}/${EXTERNAL_PROJECT_NAME}        

        GIT_REPOSITORY https://github.com/zeux/pugixml.git
        GIT_TAG "v1.9"
        GIT_PROGRESS TRUE
        
        UPDATE_COMMAND ""

        CMAKE_ARGS
            -DCMAKE_INSTALL_PREFIX=${THIRDPARTY_DIR}/${EXTERNAL_PROJECT_NAME}
            -DPROJECT_CONFIGURE_DIR=${CMAKE_DEPENDENCIES_DIR}/${EXTERNAL_PROJECT_NAME}
            -DTHIRDPARTY_DIR=${THIRDPARTY_DIR}
            -DBUILD_SHARED_LIBS=OFF
            -DBUILD_TESTS=OFF
            -DUSE_VERSIONED_LIBDIR=OFF
            -DUSE_POSTFIX=OFF
            -DBUILD_DEFINES="PUGIXML_NO_XPATH"
)

ExternalProject_Get_Property(${EXTERNAL_PROJECT_NAME}_download INSTALL_DIR)
set(EXTERNAL_PROJECT_INCLUDE_DIR ${INSTALL_DIR}/include)
set(EXTERNAL_PROJECT_LIBRARY_DIR ${INSTALL_DIR}/lib)

add_library(${EXTERNAL_PROJECT_NAME} STATIC IMPORTED)

set_target_properties(${EXTERNAL_PROJECT_NAME} PROPERTIES IMPORTED_LOCATION ${EXTERNAL_PROJECT_LIBRARY_DIR}/${CMAKE_STATIC_LIBRARY_PREFIX}${EXTERNAL_LIBRARY_FILE_NAME}${CMAKE_STATIC_LIBRARY_SUFFIX})
