set(EXTERNAL_PROJECT_NAME pybind3)

set(EXTERNAL_LIBRARY_FILE_NAME pybind3)

ExternalProject_Add(${EXTERNAL_PROJECT_NAME}_download PREFIX ${EXTERNAL_PROJECT_NAME}
        SOURCE_DIR ${DOWNLOADS_DIR}/${EXTERNAL_PROJECT_NAME}
        
        GIT_REPOSITORY https://github.com/irov/pybind.git
        GIT_PROGRESS TRUE

        UPDATE_COMMAND ""

        CMAKE_ARGS
            -DCMAKE_INSTALL_PREFIX=${THIRDPARTY_DIR}/${EXTERNAL_PROJECT_NAME}
            -DBUILD_SHARED_LIBS=OFF
            -DLIBTYPE=STATIC
            -DPYBIND_PROJECT_NAME="pybind3"
            -DPYBIND_EXTERNAL_BUILD=ON
            -DPYBIND_PYTHON_INCLUDE_PATH=${THIRDPARTY_DIR}/python3/include
            -DPYBIND_PYTHON_CONFIG_INCLUDE_PATH=${THIRDPARTY_DIR}/python3/include/PC
            -DPYBIND_STDEX_INCLUDE_PATH=${THIRDPARTY_DIR}/stdex/include
            -DPYBIND_PYTHON_VERSION=370
)

ExternalProject_Get_Property(${EXTERNAL_PROJECT_NAME}_download INSTALL_DIR)
set(EXTERNAL_PROJECT_INCLUDE_DIR ${INSTALL_DIR}/include)
set(EXTERNAL_PROJECT_LIBRARY_DIR ${INSTALL_DIR}/lib)

add_library(${EXTERNAL_PROJECT_NAME} STATIC IMPORTED)

set_target_properties(${EXTERNAL_PROJECT_NAME} PROPERTIES IMPORTED_LOCATION ${EXTERNAL_PROJECT_LIBRARY_DIR}/${CMAKE_STATIC_LIBRARY_PREFIX}${EXTERNAL_LIBRARY_FILE_NAME}${CMAKE_STATIC_LIBRARY_SUFFIX})

add_dependencies(${EXTERNAL_PROJECT_NAME}_download
    python3_download
    stdex_download
    )