set(EXTERNAL_PROJECT_NAME sdl2)

set(EXTERNAL_LIBRARY_FILE_NAME sdl2)

ExternalProject_Add(${EXTERNAL_PROJECT_NAME}_download PREFIX ${EXTERNAL_PROJECT_NAME}
        SOURCE_DIR ${DOWNLOADS_DIR}/${EXTERNAL_PROJECT_NAME}
        
        GIT_REPOSITORY https://github.com/spurious/SDL-mirror
        GIT_PROGRESS TRUE

        UPDATE_COMMAND ${CMAKE_COMMAND} -E copy
			${CMAKE_DEPENDENCIES_DIR}/${EXTERNAL_PROJECT_NAME}/SDLActivity.java
			${DOWNLOADS_DIR}/${EXTERNAL_PROJECT_NAME}/android-project/app/src/main/java/org/libsdl/app/SDLActivity.java
            ${CMAKE_DEPENDENCIES_DIR}/${EXTERNAL_PROJECT_NAME}/SDLSurface.java
			${DOWNLOADS_DIR}/${EXTERNAL_PROJECT_NAME}/android-project/app/src/main/java/org/libsdl/app/SDLSurface.java

        CMAKE_ARGS
            -DCMAKE_INSTALL_PREFIX=${THIRDPARTY_DIR}/${EXTERNAL_PROJECT_NAME}
            -DBUILD_SHARED_LIBS=OFF
            -DLIBTYPE=STATIC
            -DFORCE_STATIC_VCRT=ON
            -DSDL_SHARED=OFF
            -DSDL_STATIC=ON
            -DSDL_CMAKE_DEBUG_POSTFIX=""
)

ExternalProject_Get_Property(${EXTERNAL_PROJECT_NAME}_download INSTALL_DIR)
set(EXTERNAL_PROJECT_INCLUDE_DIR ${INSTALL_DIR}/include)
set(EXTERNAL_PROJECT_LIBRARY_DIR ${INSTALL_DIR}/lib)

add_library(${EXTERNAL_PROJECT_NAME} STATIC IMPORTED)

set_target_properties(${EXTERNAL_PROJECT_NAME} PROPERTIES IMPORTED_LOCATION ${EXTERNAL_PROJECT_LIBRARY_DIR}/${CMAKE_STATIC_LIBRARY_PREFIX}${EXTERNAL_LIBRARY_FILE_NAME}${CMAKE_STATIC_LIBRARY_SUFFIX})

