MENGINE_PROJECT(ToolMosaic)

ADD_FILTER(
src
    ToolMosaicAllocator.h
    ToolMosaicAllocator.cpp

    ToolMosaicRenderer.h
    ToolMosaicRenderer.cpp
    ToolMosaicPlatform.h
    ToolMosaicPlatform.cpp
    ToolMosaicFont.h
    ToolMosaicFont.cpp
)

INCLUDE_DIRECTORIES(SYSTEM ${THIRDPARTY_DIR}/mosaic/include)
INCLUDE_DIRECTORIES(${THIRDPARTY_DIR}/graphics/include)
INCLUDE_DIRECTORIES(${THIRDPARTY_CONFIG_DIR}/glad_gl_core_33/include)
INCLUDE_DIRECTORIES(${THIRDPARTY_DIR}/glfw3/include)
INCLUDE_DIRECTORIES(${THIRDPARTY_DIR}/freetype/include)
INCLUDE_DIRECTORIES(${THIRDPARTY_DIR}/zlib)
INCLUDE_DIRECTORIES(${THIRDPARTY_CONFIG_DIR}/zlib)

ADD_MENGINE_LIBRARY()

TARGET_LINK_LIBRARIES(${PROJECT_NAME} Kernel)

TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${THIRDPARTY_LIB_DIR}/${MENGINE_LIB_PREFIX}MosaicGraphics${MENGINE_LIB_SUFFIX})
TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${THIRDPARTY_LIB_DIR}/${MENGINE_LIB_PREFIX}MosaicCore${MENGINE_LIB_SUFFIX})
TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${THIRDPARTY_LIB_DIR}/${MENGINE_LIB_PREFIX}graphics${MENGINE_LIB_SUFFIX})
TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${THIRDPARTY_LIB_DIR}/${MENGINE_LIB_PREFIX}freetype${MENGINE_LIB_SUFFIX})
TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${THIRDPARTY_LIB_DIR}/${MENGINE_LIB_PREFIX}z${MENGINE_LIB_SUFFIX})
