# These are supported funding model platforms

 # GitHub Sponsors-enabled
github:

# Patreon
patreon: 

# Open Collective
open_collective: 

# Ko-fi
ko_fi: 

# Tidelift
tidelift:

# Community Bridge, cloud-foundry
community_bridge:

# Liberapay
liberapay: 

# IssueHunt
issuehunt:

# Otechie
otechie:

# custom sponsorship
custom:
