task:
  name: Mengine_Xcode_IOS_SDL
  
  osx_instance:
    image: mojave-xcode-10.1
    
  env:
    matrix:
      BUILD_CONFIGURATION: Debug
      BUILD_CONFIGURATION: Release
      
  install_script: brew install cmake
  
  build_script:
  - cmake --version
  
  - mkdir build_downloads_cmake
  - pushd build_downloads_cmake
  - cmake ../CMake/Downloads/ -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION
  - cmake --build .
  - popd
  
  - mkdir build_dependencies_cmake
  - pushd build_dependencies_cmake
  - cmake -G"Xcode" "$PWD/../CMake/Depends_Xcode_IOS_SDL" -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DMENGINE_DEPENDENCE_CURL=OFF -DCMAKE_TOOLCHAIN_FILE="$PWD/../dependencies/ios-cmake/ios.toolchain.cmake" -DPLATFORM=OS64 -DENABLE_BITCODE=FALSE
  - cmake --build .
  - popd
  
  - mkdir build_engine_cmake
  - pushd build_engine_cmake
  - cmake -G"Xcode" "$PWD/../CMake/Xcode_IOS_SDL" -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DMENGINE_BUILD_ONLY_EXECUTABLE_MODULE=ON -DMENGINE_PLUGIN_CURL_FORCE_DISABLE=ON -DMENGINE_LIB_DIR:STRING="Depends_Xcode_IOS_SDL" -DCMAKE_TOOLCHAIN_FILE="$PWD/../dependencies/ios-cmake/ios.toolchain.cmake" -DPLATFORM=OS64 -DENABLE_BITCODE=TRUE
  - cmake --build .
  - popd  
