version: '{build}'

branches:
  only:
  - master

image:
- Visual Studio 2019

configuration:
- Debug
- Release

environment:
  matrix:
    - ARCHITECTURE: Win32
      GENERATOR: Visual Studio 16 2019
      CMAKE_DEPENDENCIES_DIR: Depends_WIN32
      CMAKE_SOLUTION_DIR: Win32
    - ARCHITECTURE: x64
      GENERATOR: Visual Studio 16 2019
      CMAKE_DEPENDENCIES_DIR: Depends_WIN64
      CMAKE_SOLUTION_DIR: Win64
    - ARCHITECTURE: Win32
      GENERATOR: Visual Studio 16 2019
      CMAKE_DEPENDENCIES_DIR: Depends_WIN32_SDL
      CMAKE_SOLUTION_DIR: Win32_SDL
    - ARCHITECTURE: x64
      GENERATOR: Visual Studio 16 2019
      CMAKE_DEPENDENCIES_DIR: Depends_WIN64_SDL
      CMAKE_SOLUTION_DIR: Win64_SDL
    - ARCHITECTURE: Win32
      GENERATOR: Visual Studio 16 2019
      CMAKE_DEPENDENCIES_DIR: Depends_WIN32
      CMAKE_SOLUTION_DIR: Tools_Win32
    - ARCHITECTURE: x64
      GENERATOR: Visual Studio 16 2019
      CMAKE_DEPENDENCIES_DIR: Depends_WIN64
      CMAKE_SOLUTION_DIR: Tools_Win64
      

build_script:
- echo "Architecture '%ARCHITECTURE%'"
- echo "Generator '%GENERATOR%'"
- echo "Configuration '%configuration%'"
- echo "Dependencies '%CMAKE_DEPENDENCIES_DIR%'"
- echo "Solution '%CMAKE_SOLUTION_DIR%'"

- cmake --version

- echo "Downloads Dependencies"
- mkdir cmake_downloads
- cd cmake_downloads
- cmake -G "%GENERATOR%" -A %ARCHITECTURE% -S "..\cmake\Downloads" -DCMAKE_BUILD_TYPE=%configuration% -DMENGINE_DOWNLOADS_SILENT=ON
- cmake --build . --clean-first -j 4 --config %configuration% -- /verbosity:minimal
- cd ..

- echo "Build %CMAKE_DEPENDENCIES_DIR%"
- mkdir cmake_dependencies
- cd cmake_dependencies
- cmake -G "%GENERATOR%" -A %ARCHITECTURE% -S "..\cmake\%CMAKE_DEPENDENCIES_DIR%" -DCMAKE_BUILD_TYPE=%configuration%
- cmake --build . --clean-first -j 4 --config %configuration% -- /verbosity:minimal
- cd ..

- echo "Build Solution %CMAKE_SOLUTION_DIR%"
- mkdir cmake_solution
- cd cmake_solution
- cmake -G "%GENERATOR%" -A %ARCHITECTURE% -S "..\cmake\%CMAKE_SOLUTION_DIR%" -DCMAKE_BUILD_TYPE=%configuration%
- cmake --build . --clean-first -j 4 --config %configuration% -- /verbosity:minimal
- cd ..

- echo "Complete!"
