version: '{build}'

branches:
  only:
  - master

image:
- Visual Studio 2017

platform:
- x32
- x64

configuration: 
- Debug
- Release
  
init:
- if %platform%=="x32" ( set cmake_generator_arch= )
- if %platform%=="x64" ( set cmake_generator_arch= Win64 )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017"  ( set generator="Visual Studio 15 2017%cmake_generator_arch%" )
- if "%platform%"=="x32" ( set project=Win32 )
- if "%platform%"=="x64" ( set project=Win64 )

build_script:
- pushd .\CMake\Downloads
- cmake . -G %generator% -DCMAKE_BUILD_TYPE=%configuration%
- cmake --build .
- ctest --output-on-failure
- popd
- pushd .\CMake\Dependencies
- cmake . -G %generator% -DCMAKE_BUILD_TYPE=%configuration%
- cmake --build .
- ctest --output-on-failure
- popd
- pushd .\CMake\%project%
- cmake . -G %generator% -DCMAKE_BUILD_TYPE=%configuration%
- cmake --build .
- ctest --output-on-failure
- popd

test_script:
- ctest --build-config %configuration%