version: '{build}'

branches:
  only:
  - master

image:
- Visual Studio 2017

platform:
- x32
- x64

configuration: 
- Debug
- Release
  
init:
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017 %arch%" )
- if "%PLATFORM%"=="x32" ( set project=Win32 )
- if "%PLATFORM%"=="x64" ( set project=Win64 )

build_script:
- cmd: pushd .\CMake\Downloads
- cmd: cmake .. -G %generator% -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
- cmd: cmake --build .
- cmd: popd

- cmd: pushd .\CMake\Dependencies
- cmd: cmake .. -G %generator% -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
- cmd: cmake --build .
- cmd: popd

- cmd: pushd .\CMake\%project%
- cmd: cmake .. -G %generator% -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
- cmd: cmake --build .
- cmd: popd

test_script:
- cmd: ctest --build-config %configuration%