MENGINE_PROJECT(Metawrite)

ADD_FILTER(
src
    Metawrite.cpp
)

add_definitions(-DMETABUF_EXTERNAL_ALLOCATOR)

INCLUDE_DIRECTORIES(${THIRDPARTY_DIR}/metabuf/include)

LINK_DIRECTORIES( ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY} )

ADD_MENGINE_TOOL_EXECUTABLE()

TARGET_LINK_LIBRARIES(${PROJECT_NAME} ToolEngine)
