set(EXTERNAL_PROJECT_NAME openal)

if(WIN32)
    set(EXTERNAL_LIBRARY_FILE_NAME OpenAL32)
else()
    set(EXTERNAL_LIBRARY_FILE_NAME openal)
endif()

ExternalProject_Add(${EXTERNAL_PROJECT_NAME}_download PREFIX ${EXTERNAL_PROJECT_NAME}
        GIT_REPOSITORY https://github.com/kcat/openal-soft.git
        GIT_TAG "openal-soft-1.19.0"
        GIT_PROGRESS TRUE

        UPDATE_COMMAND ""

        CMAKE_ARGS
            -DCMAKE_INSTALL_PREFIX=${THIRDPARTY_DIR}/${EXTERNAL_PROJECT_NAME}
            -DBUILD_SHARED_LIBS=OFF
            -DLIBTYPE=STATIC
            -DALSOFT_BACKEND_DSOUND=OFF
            -DALSOFT_BACKEND_WASAPI=OFF
            -DALSOFT_BUILD_ROUTER=OFF
            -DALSOFT_BUILD_ROUTER=OFF
            -DALSOFT_EXAMPLES=OFF
            -DALSOFT_NO_CONFIG_UTIL=ON
            -DALSOFT_TESTS=OFF
            -DALSOFT_UTILS=OFF
)

ExternalProject_Get_Property(${EXTERNAL_PROJECT_NAME}_download INSTALL_DIR)
set(EXTERNAL_PROJECT_INCLUDE_DIR ${INSTALL_DIR}/include)
set(EXTERNAL_PROJECT_LIBRARY_DIR ${INSTALL_DIR}/lib)

add_library(${EXTERNAL_PROJECT_NAME} STATIC IMPORTED)

set_target_properties(${EXTERNAL_PROJECT_NAME} PROPERTIES IMPORTED_LOCATION ${EXTERNAL_PROJECT_LIBRARY_DIR}/${CMAKE_STATIC_LIBRARY_PREFIX}${EXTERNAL_LIBRARY_FILE_NAME}${CMAKE_STATIC_LIBRARY_SUFFIX})

