CMAKE_MINIMUM_REQUIRED(VERSION 3.24)

ADD_PLUGIN(MENGINE_PLUGIN_IMGUIFRAMEWORK ON OFF "MENGINE_PLUGIN_IMGUIFRAMEWORK")
ADD_PLUGIN(MENGINE_PLUGIN_FONTEFFECTVIEWEREXAMPLEFRAMEWORK ON OFF "MENGINE_PLUGIN_FONTEFFECTVIEWEREXAMPLEFRAMEWORK")

ADD_SUBDIRECTORY(FontEffectViewerExampleFramework)

SET(APPLICATION_LINK_LIBRARIES ${APPLICATION_LINK_LIBRARIES} PARENT_SCOPE)
SET(APPLICATION_DEPENDENCIES ${APPLICATION_DEPENDENCIES} PARENT_SCOPE)
