version: 2.1

orbs:
  android: circleci/android@2.5.0

jobs:
  build:
    executor:
      name: android/android-machine
      tag: 2025.10.1

    parallelism: 4
    
    steps:
      - checkout
      
      - android/accept-licenses
      
      - android/install-ndk:
          version: 29.0.14206865
      
      - run:
          name: install OpenJDK 17
          command: |
            sudo apt-get update && sudo apt-get install openjdk-17-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
            java -version
      
      - run:
          name: install cmake
          command: |
            echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections
            sudo apt-get install -y -q
            sudo apt-get install apt-utils -y
            sudo apt-get install cmake
            
      - run:
          name: install gradle
          command: |
            source gradle/gradle-wrapper-version.properties
            GRADLE_ARCHIVE=/tmp/gradle-${GRADLE_VERSION}-bin.zip
            curl -fsSL -o ${GRADLE_ARCHIVE} https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip
            echo "${GRADLE_DISTRIBUTION_SHA256}  ${GRADLE_ARCHIVE}" | sha256sum --check
            sudo mkdir -p /opt/gradle
            sudo rm -rf /opt/gradle/gradle-${GRADLE_VERSION}
            sudo unzip -q ${GRADLE_ARCHIVE} -d /opt/gradle
            echo "export PATH=/opt/gradle/gradle-${GRADLE_VERSION}/bin:\$PATH" >> ${BASH_ENV}
            export PATH=/opt/gradle/gradle-${GRADLE_VERSION}/bin:$PATH
            gradle --version

      - run:
          name: install ninja-build
          command: |
            sudo apt-get install ninja-build
            
      - run:
          name: sdkmanager cmake
          command: |
            yes | sdkmanager "ndk;29.0.14206865"
            yes | sdkmanager "platforms;android-36"
            yes | sdkmanager "build-tools;36.1.0"
            yes | sdkmanager "cmake;3.31.6"
          shell: /bin/bash -e
          
      - run:
          name: download dependencies
          command: |
            pushd build/downloads
            sudo bash downloads_unix.bash
            popd
            
      - run:
          name: build dependencies
          command: |
            pushd build/android_unix
            sudo bash build_depends_android.bash Debug
            popd
            
      - run:
          name: assemble
          no_output_timeout: 1h
          command: |
            sudo chown -R circleci:circleci /home/circleci/project
            bash build/android_unix/make_gradle_wrapper.sh
            pushd gradle
            cp gradle.properties.ci gradle.properties
            ./gradlew --version
            ./gradlew assembleDebug -Dorg.gradle.java.home=/usr/lib/jvm/java-17-openjdk-amd64
            popd
