CMAKE_MINIMUM_REQUIRED(VERSION 3.10)

ADD_PLUGIN(MENGINE_PLUGIN_IMGUIFRAMEWORK ON OFF "MENGINE_PLUGIN_IMGUIFRAMEWORK")
ADD_PLUGIN(MENGINE_PLUGIN_TILEDMAP ON OFF "MENGINE_PLUGIN_TILEDMAP")
ADD_PLUGIN(MENGINE_PLUGIN_TILEDMAPEXAMPLEFRAMEWORK ON OFF "MENGINE_PLUGIN_TILEDMAPEXAMPLEFRAMEWORK")

ADD_SUBDIRECTORY(TiledMapExampleFramework)

SET(APPLICATION_LINK_LIBRARIES ${APPLICATION_LINK_LIBRARIES} PARENT_SCOPE)
SET(APPLICATION_DEPENDENCIES ${APPLICATION_DEPENDENCIES} PARENT_SCOPE)
