final boolean isLibrary = project.plugins.hasPlugin('com.android.library')

final Boolean ANDROID_APP_DEBUG_MINIFY_ENABLE = Utils.getBooleanProperty("ANDROID_APP_DEBUG_MINIFY_ENABLE", false)
final Boolean ANDROID_APP_RELEASE_MINIFY_ENABLE = Utils.getBooleanProperty("ANDROID_APP_RELEASE_MINIFY_ENABLE", isLibrary == false)

final File proguardUserFile = project.file('proguard-rules.pro')

android {
    buildTypes {
        debug {
            minifyEnabled ANDROID_APP_DEBUG_MINIFY_ENABLE

            if (ANDROID_APP_DEBUG_MINIFY_ENABLE == true) {
                if (proguardUserFile.exists() == true) {
                    proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), proguardUserFile
                } else {
                    proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
                }
            }
        }

        release {
            minifyEnabled ANDROID_APP_RELEASE_MINIFY_ENABLE

            if (isLibrary == false) {
                shrinkResources ANDROID_APP_RELEASE_MINIFY_ENABLE
            }

            if (ANDROID_APP_RELEASE_MINIFY_ENABLE == true) {
                if (proguardUserFile.exists() == true) {
                    proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), proguardUserFile
                } else {
                    proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
                }
            }
        }
    }
}

if (isLibrary == true && proguardUserFile.exists() == true) {
    android {
        defaultConfig {
            consumerProguardFiles proguardUserFile
        }
    }
}
