#	include "Consts.h"

namespace Menge
{
	Consts::Consts()
	: c_builtin_empty("")
	, c_pak("pak")
	, c_zip("zip")
	, c_memory("memory")
	, c_xml2bin("xml2bin")
	, c_Default("Default")
	, c_Homeless("Homeless")
	, c_Node("Node")
	, c_Game("Game")
	, c_Entity("Entity")
	, c_Arrow("Arrow")
	, c_Scene("Scene")
	, c_Window("Window")
	, c_Image("Image")
	, c_Video("Video")
	, c_Sound("Sound")
	, c_user("user")
	, c_WhitePixel("WhitePixel")
	, c_ResourceImageDefault("ResourceImageDefault")
	, c_ResourceImageDynamic("ResourceImageDynamic")
	, c_ResourceHotspotImage("ResourceHotspotImage")
	, c_CreateImage("CreateImage")
	, c_CreateTarget("CreateTarget")
	, c_CreateTexture("CreateTexture")		
	, c_Sprite("Sprite")
	, c_Camera2D("Camera2D")
	, c_TextField("TextField")
	, c_ConsoleFont("ConsoleFont")
	, c_SoundEmitter("SoundEmitter")
	, c_RigidBody2D("RigidBody2D")
	, c_WorldPhysObject("WorldPhysObject")
	, c_NullTexture("NullTexture")
	, c_OnlyColor("OnlyColor")
	, c_ExternalAlpha("ExternalAlpha")
	, c_Debug("Debug")
	, c_ParticleIntensive("ParticleIntensive")
	, c_ParticleBlend("ParticleBlend")
	, c_Accumulator("Accumulator")
	{
	}
}