MENGINE_PROJECT(TiledMapExampleGame)

ADD_FILTER(
TiledMapExampleGame
    TiledMapExampleGame.cpp
    TiledMapExampleGame.h
    TiledMapExampleGamePlugin.cpp
    TiledMapExampleGamePlugin.h
    TiledMapExampleAutomappingHelper.cpp
    TiledMapExampleAutomappingHelper.h
    TiledMapExampleSceneEventReceiver.cpp
    TiledMapExampleSceneEventReceiver.h
)

INCLUDE_DIRECTORIES(${THIRDPARTY_CONFIG_DIR}/imgui)
INCLUDE_DIRECTORIES(${THIRDPARTY_DIR}/imgui)
INCLUDE_DIRECTORIES(${THIRDPARTY_DIR}/imgui/backends)
INCLUDE_DIRECTORIES(${THIRDPARTY_DIR}/jpp/include)

ADD_MENGINE_PLUGIN(MENGINE_PLUGIN_TILEDMAPEXAMPLEFRAMEWORK)

set_target_properties(${PROJECT_NAME} PROPERTIES
    FOLDER Game
)

TARGET_LINK_LIBRARIES(${PROJECT_NAME} Kernel)
TARGET_LINK_LIBRARIES(${PROJECT_NAME} Engine)
TARGET_LINK_LIBRARIES(${PROJECT_NAME} ImGUIFramework)
TARGET_LINK_LIBRARIES(${PROJECT_NAME} TiledMapPlugin)

TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${THIRDPARTY_LIB_DIR}/${MENGINE_LIB_PREFIX}math${MENGINE_LIB_SUFFIX})
TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${THIRDPARTY_LIB_DIR}/${MENGINE_LIB_PREFIX}imgui${MENGINE_LIB_SUFFIX})
TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${THIRDPARTY_LIB_DIR}/${MENGINE_LIB_PREFIX}jpp${MENGINE_LIB_SUFFIX})
