#pragma once

#ifdef __MENGINE_NEVER_DEFINE__
#define MENGINE_MASTER_RELEASE
#define MENGINE_USE_SCRIPT_SERVICE
#define MENGINE_RENDER_TEXTURE_RGBA
#define MENGINE_SOUND_STEREO_ONLY
#define MENGINE_ARCHITECTURE_X32
#define MENGINE_ARCHITECTURE_X64
#endif