#pragma once

#include "Config/StdInt.h"

namespace Mengine
{
    typedef uint64_t Timestamp;

    static const Timestamp TIMESTAMP_MILLISECONDS_SECOND64 = 1000ULL;
    static const Timestamp TIMESTAMP_MILLISECONDS_MINUTE64 = TIMESTAMP_MILLISECONDS_SECOND64 * 60ULL;
    static const Timestamp TIMESTAMP_MILLISECONDS_HOUR64 = TIMESTAMP_MILLISECONDS_MINUTE64 * 60ULL;
    static const Timestamp TIMESTAMP_MILLISECONDS_DAY64 = TIMESTAMP_MILLISECONDS_HOUR64 * 24ULL;
    static const Timestamp TIMESTAMP_MILLISECONDS_MONTH64 = TIMESTAMP_MILLISECONDS_DAY64 * 31ULL;
    static const Timestamp TIMESTAMP_MILLISECONDS_YEAR64 = TIMESTAMP_MILLISECONDS_MONTH64 * 12ULL;
}