#pragma once

#include "Config/StdInt.h"

namespace Mengine
{
    typedef uint64_t Timestamp;

    static const Timestamp TIMESTAMP_MILLISECONDS_SECOND64 = MENGINE_UINT64_C( 1000 );
    static const Timestamp TIMESTAMP_MILLISECONDS_MINUTE64 = TIMESTAMP_MILLISECONDS_SECOND64 * MENGINE_UINT64_C( 60 );
    static const Timestamp TIMESTAMP_MILLISECONDS_HOUR64 = TIMESTAMP_MILLISECONDS_MINUTE64 * MENGINE_UINT64_C( 60 );
    static const Timestamp TIMESTAMP_MILLISECONDS_DAY64 = TIMESTAMP_MILLISECONDS_HOUR64 * MENGINE_UINT64_C( 24 );
    static const Timestamp TIMESTAMP_MILLISECONDS_MONTH64 = TIMESTAMP_MILLISECONDS_DAY64 * MENGINE_UINT64_C( 31 );
    static const Timestamp TIMESTAMP_MILLISECONDS_YEAR64 = TIMESTAMP_MILLISECONDS_MONTH64 * MENGINE_UINT64_C( 12 );
}