#pragma once

#include "Config/Config.h"

#define MENGINE_MAJOR_VERSION   1
#define MENGINE_MINOR_VERSION   0
#define MENGINE_PATCHLEVEL      0

#define MENGINE_VERSION_STRING MENGINE_PP_STRINGIZE(MENGINE_MAJOR_VERSION) "." MENGINE_PP_STRINGIZE(MENGINE_MINOR_VERSION) "." MENGINE_PP_STRINGIZE(MENGINE_PATCHLEVEL)

#define MENGINE_VERSION_NUMBER (MENGINE_MAJOR_VERSION << 16 | MENGINE_MINOR_VERSION << 8 | MENGINE_PATCHLEVEL)
