#pragma once

#include "Config/Config.h"

#define MENGINE_ENGINE_VERSION_MAJOR 1
#define MENGINE_ENGINE_VERSION_MINOR 0
#define MENGINE_ENGINE_VERSION_PATCH 0

#define MENGINE_ENGINE_VERSION_STRING MENGINE_PP_STRINGIZE(MENGINE_ENGINE_VERSION_MAJOR) "." MENGINE_PP_STRINGIZE(MENGINE_ENGINE_VERSION_MINOR) "." MENGINE_PP_STRINGIZE(MENGINE_ENGINE_VERSION_PATCH)

#define MENGINE_ENGINE_VERSION_NUMBER (MENGINE_ENGINE_VERSION_MAJOR << 16 | MENGINE_ENGINE_VERSION_MINOR << 8 | MENGINE_ENGINE_VERSION_PATCH)
