VK_UNASSIGNED  = 0x00
VK_ESC         = 0x01
VK_1           = 0x02
VK_2           = 0x03
VK_3           = 0x04
VK_4           = 0x05
VK_5           = 0x06
VK_6           = 0x07
VK_7           = 0x08
VK_8           = 0x09
VK_9           = 0x0A
VK_0           = 0x0B
VK_MINUS       = 0x0C    # - on main keyboard
VK_EQUALS      = 0x0D
VK_BACK        = 0x0E    # backspace
VK_TAB         = 0x0F
VK_Q           = 0x10
VK_W           = 0x11
VK_E           = 0x12
VK_R           = 0x13
VK_T           = 0x14
VK_Y           = 0x15
VK_U           = 0x16
VK_I           = 0x17
VK_O           = 0x18
VK_P           = 0x19
VK_LBRACKET    = 0x1A
VK_RBRACKET    = 0x1B
VK_ENTER       = 0x1C    # Enter on main keyboard
VK_LCONTROL    = 0x1D
VK_A           = 0x1E
VK_S           = 0x1F
VK_D           = 0x20
VK_F           = 0x21
VK_G           = 0x22
VK_H           = 0x23
VK_J           = 0x24
VK_K           = 0x25
VK_L           = 0x26
VK_SEMICOLON   = 0x27
VK_APOSTROPHE  = 0x28
VK_GRAVE       = 0x29    # accent
VK_LSHIFT      = 0x2A
VK_BACKSLASH   = 0x2B
VK_Z           = 0x2C
VK_X           = 0x2D
VK_C           = 0x2E
VK_V           = 0x2F
VK_B           = 0x30
VK_N           = 0x31
VK_M           = 0x32
VK_COMMA       = 0x33
VK_PERIOD      = 0x34    # . on main keyboard
VK_SLASH       = 0x35    # / on main keyboard
VK_RSHIFT      = 0x36
VK_MULTIPLY    = 0x37    # * on numeric keypad
VK_LMENU       = 0x38    # left Alt
VK_SPACE       = 0x39
VK_CAPITAL     = 0x3A
VK_F1          = 0x3B
VK_F2          = 0x3C
VK_F3          = 0x3D
VK_F4          = 0x3E
VK_F5          = 0x3F
VK_F6          = 0x40
VK_F7          = 0x41
VK_F8          = 0x42
VK_F9          = 0x43
VK_F10         = 0x44
VK_NUMLOCK     = 0x45
VK_SCROLL      = 0x46    # Scroll Lock
VK_NUMPAD7     = 0x47
VK_NUMPAD8     = 0x48
VK_NUMPAD9     = 0x49
VK_SUBTRACT    = 0x4A    # - on numeric keypad
VK_NUMPAD4     = 0x4B
VK_NUMPAD5     = 0x4C
VK_NUMPAD6     = 0x4D
VK_ADD         = 0x4E    # + on numeric keypad
VK_NUMPAD1     = 0x4F
VK_NUMPAD2     = 0x50
VK_NUMPAD3     = 0x51
VK_NUMPAD0     = 0x52
VK_DECIMAL     = 0x53    # . on numeric keypad
VK_OEM_102     = 0x56    # < > | on UK/Germany keyboards
VK_F11         = 0x57
VK_F12         = 0x58
VK_F13         = 0x64    #                     (NEC PC98)
VK_F14         = 0x65    #                     (NEC PC98)
VK_F15         = 0x66    #                     (NEC PC98)
VK_KANA        = 0x70    # (Japanese keyboard)
VK_ABNT_C1     = 0x73    # / ? on Portugese (Brazilian) keyboards
VK_CONVERT     = 0x79    # (Japanese keyboard)
VK_NOCONVERT   = 0x7B    # (Japanese keyboard)
VK_YEN         = 0x7D    # (Japanese keyboard)
VK_ABNT_C2     = 0x7E    # Numpad . on Portugese (Brazilian) keyboards
VK_NUMPADEQUALS= 0x8D    # = on numeric keypad (NEC PC98)
VK_PREVTRACK   = 0x90    # Previous Track (VK_CIRCUMFLEX on Japanese keyboard)
VK_AT          = 0x91    #                     (NEC PC98)
VK_COLON       = 0x92    #                     (NEC PC98)
VK_UNDERLINE   = 0x93    #                     (NEC PC98)
VK_KANJI       = 0x94    # (Japanese keyboard)
VK_STOP        = 0x95    #                     (NEC PC98)
VK_AX          = 0x96    #                     (Japan AX)
VK_UNLABELED   = 0x97    #                        (J3100)
VK_NEXTTRACK   = 0x99    # Next Track
VK_NUMPADENTER = 0x9C    # Enter on numeric keypad
VK_RCONTROL    = 0x9D
VK_MUTE        = 0xA0    # Mute
VK_CALCULATOR  = 0xA1    # Calculator
VK_PLAYPAUSE   = 0xA2    # Play / Pause
VK_MEDIASTOP   = 0xA4    # Media Stop
VK_VOLUMEDOWN  = 0xAE    # Volume -
VK_VOLUMEUP    = 0xB0    # Volume +
VK_WEBHOME     = 0xB2    # Web home
VK_NUMPADCOMMA = 0xB3    # , on numeric keypad (NEC PC98)
VK_DIVIDE      = 0xB5    # / on numeric keypad
VK_SYSRQ       = 0xB7
VK_RMENU       = 0xB8    # right Alt
VK_PAUSE       = 0xC5    # Pause
VK_HOME        = 0xC7    # Home on arrow keypad
VK_UP          = 0xC8    # UpArrow on arrow keypad
VK_PGUP        = 0xC9    # PgUp on arrow keypad
VK_LEFT        = 0xCB    # LeftArrow on arrow keypad
VK_RIGHT       = 0xCD    # RightArrow on arrow keypad
VK_END         = 0xCF    # End on arrow keypad
VK_DOWN        = 0xD0    # DownArrow on arrow keypad
VK_PGDOWN      = 0xD1    # PgDn on arrow keypad
VK_INSERT      = 0xD2    # Insert on arrow keypad
VK_DELETE      = 0xD3    # Delete on arrow keypad
VK_LWIN        = 0xDB    # Left Windows key
VK_RWIN        = 0xDC    # Right Windows key
VK_APPS        = 0xDD    # AppMenu key
VK_POWER       = 0xDE    # System Power
VK_SLEEP       = 0xDF    # System Sleep
VK_WAKE        = 0xE3    # System Wake
VK_WEBSEARCH   = 0xE5    # Web Search
VK_WEBFAVORITES= 0xE6    # Web Favorites
VK_WEBREFRESH  = 0xE7    # Web Refresh
VK_WEBSTOP     = 0xE8    # Web Stop
VK_WEBFORWARD  = 0xE9    # Web Forward
VK_WEBBACK     = 0xEA    # Web Back
VK_MYCOMPUTER  = 0xEB    # My Computer
VK_MAIL        = 0xEC    # Mail
VK_MEDIASELECT = 0xED    # Media Select
