get_filename_component(FONT_EFFECT_VIEWER_SHARED_SHADERS_PATH "${MENGINE_DEPLOY_PATH}/../../shaders" ABSOLUTE)

if(NOT EXISTS "${FONT_EFFECT_VIEWER_SHARED_SHADERS_PATH}/Pak.json")
    message(FATAL_ERROR "FontEffectViewer shared shaders package not found '${FONT_EFFECT_VIEWER_SHARED_SHADERS_PATH}/Pak.json'")
endif()

file(GLOB FONT_EFFECT_VIEWER_SHARED_SHADER_MATERIALS
    "${FONT_EFFECT_VIEWER_SHARED_SHADERS_PATH}/Materials/*.json"
    "${FONT_EFFECT_VIEWER_SHARED_SHADERS_PATH}/Materials/*.txt"
)

set(FONT_EFFECT_VIEWER_BUNDLE_SHADERS_PATH "$<TARGET_FILE_DIR:${PROJECT_NAME}>/../Resources/Data/shaders")

add_custom_command(TARGET ${PROJECT_NAME} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E make_directory
        "${FONT_EFFECT_VIEWER_BUNDLE_SHADERS_PATH}/Materials"
    COMMAND ${CMAKE_COMMAND} -E copy_if_different
        "${FONT_EFFECT_VIEWER_SHARED_SHADERS_PATH}/Pak.json"
        "${FONT_EFFECT_VIEWER_BUNDLE_SHADERS_PATH}/Pak.json"
)

foreach(FONT_EFFECT_VIEWER_SHARED_SHADER_MATERIAL ${FONT_EFFECT_VIEWER_SHARED_SHADER_MATERIALS})
    add_custom_command(TARGET ${PROJECT_NAME} POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E copy_if_different
            "${FONT_EFFECT_VIEWER_SHARED_SHADER_MATERIAL}"
            "${FONT_EFFECT_VIEWER_BUNDLE_SHADERS_PATH}/Materials"
    )
endforeach()
