#import "Environment/iOS/UIKitProxyApplicationDelegateBase.h"

@interface AppleUserNotificationCenterApplicationDelegate : NSObject<UIKitProxyApplicationDelegateInterface, UNUserNotificationCenterDelegate>

@end