MENGINE_PROJECT(TiledMapPlugin)

ADD_FILTER(
src
    TiledMapPlugin.cpp
    TiledMapPlugin.h
    TiledMapPlugin.def

    ResourceTiledMap.cpp
    ResourceTiledMap.h
    TiledMap2D.cpp
    TiledMap2D.h
)

ADD_FILTER(
Metabuf
    MetabufLoaderResourceTiledMap.cpp
    MetabufLoaderResourceTiledMap.h
)

add_definitions(-DMETABUF_EXTERNAL_ALLOCATOR)
INCLUDE_DIRECTORIES(${THIRDPARTY_DIR}/metabuf/include)

if(MENGINE_BUILD_MENGINE_SCRIPT_EMBEDDED)
    ADD_FILTER(
    embedding
        TiledMapScriptEmbedding.cpp
        TiledMapScriptEmbedding.h
    )

    INCLUDE_DIRECTORIES(${THIRDPARTY_DIR}/pybind/include)
endif()

INCLUDE_DIRECTORIES(${THIRDPARTY_DIR}/graphics/include)
INCLUDE_DIRECTORIES(${THIRDPARTY_DIR}/jpp/include)
INCLUDE_DIRECTORIES(${THIRDPARTY_CONFIG_DIR}/zlib)
INCLUDE_DIRECTORIES(${THIRDPARTY_DIR}/zlib)
INCLUDE_DIRECTORIES(${THIRDPARTY_DIR}/zstd/lib)

ADD_MENGINE_PLUGIN(MENGINE_PLUGIN_TILEDMAP)

if(MENGINE_BUILD_MENGINE_SCRIPT_EMBEDDED)
    TARGET_LINK_LIBRARIES(${PROJECT_NAME} Python)
endif()

TARGET_LINK_LIBRARIES(${PROJECT_NAME} Kernel)
TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${THIRDPARTY_LIB_DIR}/${MENGINE_LIB_PREFIX}graphics${MENGINE_LIB_SUFFIX})
TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${THIRDPARTY_LIB_DIR}/${MENGINE_LIB_PREFIX}zstd${MENGINE_LIB_SUFFIX})

if(WIN32)
    TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${THIRDPARTY_LIB_DIR}/${MENGINE_LIB_PREFIX}zs${MENGINE_DEPENDENCIES_DEBUG_SUFFIX}${MENGINE_LIB_SUFFIX})
else()
    TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${THIRDPARTY_LIB_DIR}/${MENGINE_LIB_PREFIX}z${MENGINE_LIB_SUFFIX})
endif()

TARGET_LINK_LIBRARIES(${PROJECT_NAME} Metacode)
TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${THIRDPARTY_LIB_DIR}/${MENGINE_LIB_PREFIX}metabuf${MENGINE_LIB_SUFFIX})
