MENGINE_PROJECT(AstralaxCompiler)

ADD_FILTER(
src
    AstralaxCompiler.cpp
)

add_definitions(-DUNICODE)
add_definitions(-D_UNICODE)

if(MENGINE_TOOLCHAIN_MINGW AND MENGINE_ARCHITECTURE_X86)
    set(MENGINE_ASTRALAX_COMPILER_DIR "${THIRDPARTY_DIR}/astralax_win32/mingw32")
elseif(MENGINE_TOOLCHAIN_MINGW AND MENGINE_ARCHITECTURE_X64)
    set(MENGINE_ASTRALAX_COMPILER_DIR "${THIRDPARTY_DIR}/astralax_win32/mingw64")
elseif(MENGINE_TOOLCHAIN_MSVC AND MENGINE_ARCHITECTURE_X86)
    set(MENGINE_ASTRALAX_COMPILER_DIR "${THIRDPARTY_DIR}/astralax_win32/mingw32")
elseif(MENGINE_TARGET_MACOS)
    set(MENGINE_ASTRALAX_COMPILER_DIR "${THIRDPARTY_DIR}/astralax_macos")
else()
    message(FATAL_ERROR "AstralaxCompiler requires an Astralax package for the selected toolchain and architecture")
endif()

INCLUDE_DIRECTORIES(
    ${MENGINE_ASTRALAX_COMPILER_DIR}/include
    ${THIRDPARTY_DIR}/lz4/lib
    ${THIRDPARTY_DIR}/libmath/include
)

LINK_DIRECTORIES(${CMAKE_ARCHIVE_OUTPUT_DIRECTORY})
ADD_MENGINE_TOOL_EXECUTABLE()

if(MENGINE_TARGET_WINDOWS)
    TARGET_COMPILE_DEFINITIONS(${PROJECT_NAME} PRIVATE ASTRALAX_BUILD_SHARED)
    TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${MENGINE_ASTRALAX_COMPILER_DIR}/lib/libastralax.a)
elseif(MENGINE_TARGET_MACOS)
    TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${MENGINE_ASTRALAX_COMPILER_DIR}/lib/libastralax.dylib)
    SET_TARGET_PROPERTIES(${PROJECT_NAME} PROPERTIES BUILD_RPATH "${MENGINE_ASTRALAX_COMPILER_DIR}/lib" INSTALL_RPATH "@loader_path")
endif()

TARGET_LINK_LIBRARIES(${PROJECT_NAME}
    ${THIRDPARTY_LIB_DIR}/${MENGINE_LIB_PREFIX}lz4${MENGINE_LIB_SUFFIX}
    ${THIRDPARTY_LIB_DIR}/${MENGINE_LIB_PREFIX}math${MENGINE_LIB_SUFFIX}
    ToolUtils
)
