MENGINE_PROJECT(AekCompiler)

ADD_FILTER(
src
    AekCompiler.cpp
    XmlToAekConverter.cpp
    XmlToAekConverter.h
)

add_definitions(-DMETABUF_EXTERNAL_CONFIG)

INCLUDE_DIRECTORIES(${THIRDPARTY_DIR}/metabuf/include)
INCLUDE_DIRECTORIES(${THIRDPARTY_DIR}/metabuf/src/xml2metabuf)
INCLUDE_DIRECTORIES(${THIRDPARTY_DIR}/pugixml/src)

ADD_MENGINE_TOOL_EXECUTABLE()

TARGET_LINK_LIBRARIES(${PROJECT_NAME} ToolEngine)
TARGET_LINK_LIBRARIES(${PROJECT_NAME} Metacode)
TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${THIRDPARTY_LIB_DIR}/${MENGINE_LIB_PREFIX}metabuf${MENGINE_LIB_SUFFIX})
TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${THIRDPARTY_LIB_DIR}/${MENGINE_LIB_PREFIX}pugixml${MENGINE_LIB_SUFFIX})
