# SET LIBNAME
set(CMAKE_DEBUG_POSTFIX "d")

set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_C_COMPILER clang)

SET( MENGINE_LIB_PREFIX "lib" )
SET( MENGINE_LIB_SUFFIX ".a" )

SET( MENGINE_LIB_POSTFIX ${MENGINE_LIB_SUFFIX} )

SET( MENGINE_LIB_SUFFIXD ${CMAKE_DEBUG_POSTFIX}${MENGINE_LIB_SUFFIX} )

SET(TARGETSDK_NAME iPhoneSimulator)
SET(TARGETSDK_VERSION 5.0)
SET(CMAKE_OSX_SYSROOT /Developer/Platforms/${TARGETSDK_NAME}.platform/Developer/SDKs/${TARGETSDK_NAME}${TARGETSDK_VERSION}.sdk)
SET(CMAKE_FRAMEWORK_PATH ${CMAKE_OSX_SYSROOT}/System/Library/Frameworks)

#set(CMAKE_OSX_ARCHITECTURES "$(ARCHS_STANDARD_32_BIT)")
SET(CMAKE_OSX_ARCHITECTURES "armv7")

set(CMAKE_XCODE_EFFECTIVE_PLATFORMS "-iphoneos;-iphonesimulator")


 






