MENGINE_PROJECT(Ravinggen)

ADD_FILTER(
src
    Ravinggen.cpp
)

LINK_DIRECTORIES(${CMAKE_ARCHIVE_OUTPUT_DIRECTORY})
ADD_MENGINE_TOOL_EXECUTABLE()


TARGET_LINK_LIBRARIES(${PROJECT_NAME} ToolUtils)
TARGET_LINK_LIBRARIES(${PROJECT_NAME} Kernel)

TARGET_LINK_LIBRARIES(${PROJECT_NAME}
    ${THIRDPARTY_LIB_DIR}/${MENGINE_LIB_PREFIX}math${MENGINE_LIB_SUFFIX}
)

if(WIN32)
    TARGET_LINK_LIBRARIES(${PROJECT_NAME} Shlwapi comctl32)
endif()
