include_guard(GLOBAL)

function(arena3d_download_content)
    get_filename_component(ARENA3D_ROOT "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../.." ABSOLUTE)
    set(MENGINE_DOWNLOADS_PATH "${ARENA3D_ROOT}/resources/.downloads")
    include("${ARENA3D_ROOT}/../../cmake/download_template.cmake")

    foreach(GROUP q3dm6ish_v2 openarena_models)
        set(MANIFEST_PATH "${ARENA3D_ROOT}/content/third_party/${GROUP}/sources.json")
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${MANIFEST_PATH}")
        file(READ "${MANIFEST_PATH}" MANIFEST)
        string(JSON FILE_COUNT LENGTH "${MANIFEST}")
        math(EXPR LAST_FILE "${FILE_COUNT} - 1")
        foreach(INDEX RANGE ${LAST_FILE})
            string(JSON FILE_PATH GET "${MANIFEST}" ${INDEX} path)
            string(JSON FILE_URL GET "${MANIFEST}" ${INDEX} url)
            string(JSON FILE_SHA256 GET "${MANIFEST}" ${INDEX} sha256)
            DOWNLOAD_FILE_HASH("${GROUP}" "${FILE_URL}" "${FILE_PATH}" "${FILE_SHA256}")
        endforeach()
    endforeach()
endfunction()
