MESSAGE("CMAKE_GENERATOR: ${CMAKE_GENERATOR}")
MESSAGE("CMAKE_BUILD_TYPE: ${CMAKE_BUILD_TYPE}")

set_property(GLOBAL PROPERTY USE_FOLDERS ON)

SET(MENGINE_REPOSITORY ${CMAKE_CURRENT_SOURCE_DIR}/../..)

IF(NOT MENGINE_INSTALL_PATH)
    SET(MENGINE_INSTALL_PATH ${MENGINE_REPOSITORY}/bin)
ENDIF()

MESSAGE("MENGINE_INSTALL_PATH: ${MENGINE_INSTALL_PATH}")

IF(NOT MENGINE_PDB_PATH)
    SET(MENGINE_PDB_PATH ${MENGINE_REPOSITORY}/pdb)
ENDIF()

MESSAGE("MENGINE_PDB_PATH: ${MENGINE_PDB_PATH}")

if(UNIX AND NOT ANDROID)
    # input and thirdparty paths
    SET(THIRDPARTY_DIR ${MENGINE_REPOSITORY}/dependencies)
    SET(THIRDPARTY_LIB_DIR ${MENGINE_REPOSITORY}/lib/dependencies/${CMAKE_GENERATOR}/${CMAKE_BUILD_TYPE})
elseif(ANDROID)
    # input and thirdparty paths
    SET(THIRDPARTY_DIR ${MENGINE_REPOSITORY}/dependencies)
    SET(THIRDPARTY_LIB_DIR ${MENGINE_REPOSITORY}/lib/dependencies/${CMAKE_GENERATOR}/${CMAKE_BUILD_TYPE}/${ANDROID_ABI})
elseif(MINGW)
    # input and thirdparty paths
    SET(THIRDPARTY_DIR ${MENGINE_REPOSITORY}/dependencies)
    SET(THIRDPARTY_LIB_DIR ${MENGINE_REPOSITORY}/lib/dependencies/${CMAKE_GENERATOR}/${CMAKE_BUILD_TYPE})
elseif(APPLE)
    # input and thirdparty paths
    SET(THIRDPARTY_DIR ${MENGINE_REPOSITORY}/dependencies)
    SET(THIRDPARTY_LIB_DIR ${MENGINE_REPOSITORY}/lib/dependencies/${CMAKE_GENERATOR}/${CMAKE_BUILD_TYPE})
else()
    # input and thirdparty paths
    SET(THIRDPARTY_DIR ${MENGINE_REPOSITORY}/dependencies)
    SET(THIRDPARTY_LIB_DIR ${MENGINE_REPOSITORY}/lib/dependencies/${CMAKE_GENERATOR}/${CMAKE_BUILD_TYPE})    
endif()

MESSAGE("THIRDPARTY_DIR: ${THIRDPARTY_DIR}")
MESSAGE("THIRDPARTY_LIB_DIR: ${THIRDPARTY_LIB_DIR}")

SET(MENGINE_CMAKE_DEPENDENCIES_DIR ${MENGINE_REPOSITORY}/cmake/Dependencies)
SET(MENGINE_SOURCE_DIR ${MENGINE_REPOSITORY}/src)