OPTION(MENGINE_USE_ADDRESS_SANITIZE "Mengine use address sanitize" OFF)
SET(MENGINE_PYBIND_BACKEND "python" CACHE STRING "pybind backend: python or tinypy")
SET(MENGINE_TINYPY_SOURCE_DIR "" CACHE PATH "Optional tinypy source directory override")
SET_PROPERTY(CACHE MENGINE_PYBIND_BACKEND PROPERTY STRINGS python tinypy)

IF(NOT MENGINE_PYBIND_BACKEND STREQUAL "python" AND NOT MENGINE_PYBIND_BACKEND STREQUAL "tinypy")
    MESSAGE(FATAL_ERROR "MENGINE_PYBIND_BACKEND must be python or tinypy")
ENDIF()

OPTION(MENGINE_USE_PRECOMPILED_HEADER "Mengine use precompiled header" OFF)
