CMAKE_MINIMUM_REQUIRED( VERSION 2.6 )

IF(CMAKE_BUILD_TYPE MATCHES "Debug")
    SET(MENGINE_DEPENDENCIES_DEBUG_SUFFIX "d")
ELSE()
    SET(MENGINE_DEPENDENCIES_DEBUG_SUFFIX "")
ENDIF()

MACRO(SET_MENGINE_ENVIRONMENT MENGINE_FRAMEWORK MENGINE_TARGET MENGINE_RENDER MENGINE_ARCHITECTURE MENGINE_PLATFORM MENGINE_TOOLCHAIN)
    
    SET(MENGINE_FRAMEWORK_PYTHON OFF CACHE BOOL "MENGINE_FRAMEWORK_PYTHON" FORCE)

    SET(MENGINE_TARGET_WINDOWS OFF CACHE BOOL "MENGINE_TARGET_WINDOWS" FORCE)
    SET(MENGINE_TARGET_ANDROID OFF CACHE BOOL "MENGINE_TARGET_ANDROID" FORCE)
    SET(MENGINE_TARGET_MACOS OFF CACHE BOOL "MENGINE_TARGET_MACOS" FORCE)
    SET(MENGINE_TARGET_IOS OFF CACHE BOOL "MENGINE_TARGET_MACOS" FORCE)

    SET(MENGINE_RENDER_OPENGL OFF CACHE BOOL "MENGINE_RENDER_OPENGL" FORCE)
    SET(MENGINE_RENDER_DIRECTX OFF CACHE BOOL "MENGINE_RENDER_DIRECTX" FORCE)

    SET(MENGINE_ARCHITECTURE_X86 OFF CACHE BOOL "MENGINE_ARCHITECTURE_X86" FORCE)
    SET(MENGINE_ARCHITECTURE_X64 OFF CACHE BOOL "MENGINE_ARCHITECTURE_X64" FORCE)

    SET(MENGINE_PLATFORM_SDL OFF CACHE BOOL "MENGINE_PLATFORM_SDL" FORCE)
    SET(MENGINE_PLATFORM_WIN32 OFF CACHE BOOL "MENGINE_PLATFORM_WIN32" FORCE)

    SET(MENGINE_TOOLCHAIN_MSVC OFF CACHE BOOL "MENGINE_TOOLCHAIN_MSVC" FORCE)
    SET(MENGINE_TOOLCHAIN_MINGW OFF CACHE BOOL "MENGINE_TOOLCHAIN_MINGW" FORCE)
    SET(MENGINE_TOOLCHAIN_GRADLE OFF CACHE BOOL "MENGINE_TOOLCHAIN_GRADLE" FORCE)
    SET(MENGINE_TOOLCHAIN_XCODE_MAC OFF CACHE BOOL "MENGINE_TOOLCHAIN_XCODE_MAC" FORCE)
    SET(MENGINE_TOOLCHAIN_XCODE_IOS OFF CACHE BOOL "MENGINE_TOOLCHAIN_XCODE_IOS" FORCE)
    
    SET(MENGINE_FRAMEWORK_${MENGINE_FRAMEWORK} ON CACHE BOOL "MENGINE_FRAMEWORK" FORCE)
    SET(MENGINE_TARGET_${MENGINE_TARGET} ON CACHE BOOL "MENGINE_TARGET" FORCE)
    SET(MENGINE_RENDER_${MENGINE_RENDER} ON CACHE BOOL "MENGINE_RENDER" FORCE)
    SET(MENGINE_ARCHITECTURE_${MENGINE_ARCHITECTURE} ON CACHE BOOL "MENGINE_ARCHITECTURE" FORCE)    
    SET(MENGINE_PLATFORM_${MENGINE_PLATFORM} ON CACHE BOOL "MENGINE_PLATFORM" FORCE)
    SET(MENGINE_TOOLCHAIN_${MENGINE_TOOLCHAIN} ON CACHE BOOL "MENGINE_TOOLCHAIN" FORCE)
        
    MESSAGE("*********************************************")
    MESSAGE("ENABLE MENGINE_FRAMEWORK = ${MENGINE_FRAMEWORK}")
    MESSAGE("ENABLE MENGINE_TARGET = ${MENGINE_TARGET}")
    MESSAGE("ENABLE MENGINE_RENDER = ${MENGINE_RENDER}")
    MESSAGE("ENABLE MENGINE_ARCHITECTURE = ${MENGINE_ARCHITECTURE}")
    MESSAGE("ENABLE MENGINE_PLATFORM = ${MENGINE_PLATFORM}")
    MESSAGE("ENABLE MENGINE_TOOLCHAIN = ${MENGINE_TOOLCHAIN}")
    MESSAGE("*********************************************")
ENDMACRO()

MACRO(ADD_FILTER group_name)
	SOURCE_GROUP( ${group_name} FILES ${ARGN} )
	SET( SRC_FILES ${SRC_FILES} ${ARGN} )
	#MESSAGE( ${ARGN} )
ENDMACRO()
# solution

MACRO(ADD_PLUGIN Plugin Toggle DLL MSG)
    SET(${Plugin} ${Toggle} CACHE BOOL ${MSG} FORCE)
    
    IF(${Plugin})
        SET(${Plugin}_DLL ${DLL} CACHE BOOL ${MSG} FORCE)
        
        IF(${Plugin}_DLL)
            SET(${Plugin}_STATIC OFF CACHE BOOL ${MSG} FORCE)
        ELSE()
            SET(${Plugin}_STATIC ON CACHE BOOL ${MSG} FORCE)
        ENDIF()
        
        add_definitions(-D${Plugin})
    ENDIF()
    
    IF(${Plugin})
        IF(${Plugin}_DLL)
            add_definitions(-D${Plugin}_DLL)
        ELSE()
            add_definitions(-D${Plugin}_STATIC)
        ENDIF()
    ENDIF()
ENDMACRO()

MACRO(CREATE_PRECOMPILED_HEADER)
  IF(MSVC)
	SET(PrecompiledHeader "PrecompiledHeader.h")
	SET(PrecompiledSource "${MENGINE_SOURCE_DIR}/PrecompiledHeader/PrecompiledHeader.cpp")
    SET(PrecompiledBinary "${MENGINE_SOURCE_DIR}/PrecompiledHeader/PrecompiledHeader.pch")

    SET_SOURCE_FILES_PROPERTIES(${PrecompiledSource}
                                PROPERTIES COMPILE_FLAGS "/Yc\"${PrecompiledHeader}\" /FI\"${PrecompiledHeader}\" /Fp\"${PrecompiledBinary}\""
                                           OBJECT_OUTPUTS "${PrecompiledBinary}")
  ENDIF()
ENDMACRO()

MACRO(ADD_PRECOMPILED_HEADER)
  IF(MSVC)
	SET(PrecompiledHeader "PrecompiledHeader.h")
    SET(PrecompiledBinary "${MENGINE_SOURCE_DIR}/PrecompiledHeader/PrecompiledHeader.pch")

    SET_SOURCE_FILES_PROPERTIES(${SRC_FILES}
                                PROPERTIES COMPILE_FLAGS "/Yu\"${PrecompiledHeader}\" /FI\"${PrecompiledHeader}\" /Fp\"${PrecompiledBinary}\""
                                           )  
										   #OBJECT_DEPENDS "${PrecompiledBinary}"
  ENDIF()
ENDMACRO()

MACRO(ADD_MENGINE_LIBRARY)
	#ADD_PRECOMPILED_HEADER()

	ADD_LIBRARY( ${MY_LIB_NAME} STATIC ${SRC_FILES})
	
	#ADD_DEPENDENCIES( ${MY_LIB_NAME} PrecompiledHeader )
ENDMACRO()

MACRO(ADD_MENGINE_SHARED)
	#ADD_PRECOMPILED_HEADER()

	ADD_LIBRARY( ${MY_LIB_NAME} SHARED ${SRC_FILES})
	
	SET_TARGET_PROPERTIES( ${MY_LIB_NAME} 
		PROPERTIES PREFIX ""
		)
	
	#ADD_DEPENDENCIES( ${MY_LIB_NAME} PrecompiledHeader )
ENDMACRO()

MACRO(ADD_MENGINE_PLUGIN PLUGIN_NAME)
    IF(${PLUGIN_NAME}_DLL)
        add_definitions(-DMENGINE_PLUGIN_DLL)
        ADD_MENGINE_SHARED()
    ELSE()
        ADD_MENGINE_LIBRARY()
    ENDIF()
ENDMACRO()

if(APPLE)
  macro(ADD_FRAMEWORK appname fwname)
    find_library(FRAMEWORK_${fwname}
        NAMES ${fwname}
        PATHS ${CMAKE_OSX_SYSROOT}/System/Library
        PATH_SUFFIXES Frameworks
        NO_DEFAULT_PATH)
    if( ${FRAMEWORK_${fwname}} STREQUAL FRAMEWORK_${fwname}-NOTFOUND)
        MESSAGE(ERROR ": Framework ${fwname} not found")
    else()
        TARGET_LINK_LIBRARIES(${appname} ${FRAMEWORK_${fwname}})
        MESSAGE(STATUS "Framework ${fwname} found at ${FRAMEWORK_${fwname}}")
    endif()
  endmacro()
endif()