if(MENGINE_BUILD_MENGINE_MASTER_RELEASE)
    ADD_DEFINITIONS(-DMENGINE_MASTER_RELEASE)
endif()

if(MENGINE_BUILD_MENGINE_BUILD_PUBLISH)
    ADD_DEFINITIONS(-DMENGINE_BUILD_PUBLISH)
endif()

if(MENGINE_BUILD_MENGINE_LOGGER_LEVEL_FORCE_VERBOSE)
    ADD_DEFINITIONS(-DMENGINE_LOGGER_LEVEL_FORCE_VERBOSE=1)
endif()

if(MENGINE_BUILD_MENGINE_DEVELOPMENT)
    ADD_DEFINITIONS(-DMENGINE_BUILD_DEVELOPMENT)
endif()

if(MENGINE_USE_SCRIPT_SERVICE)
    ADD_DEFINITIONS(-DMENGINE_USE_SCRIPT_SERVICE)
endif()

if(MENGINE_SECURE_VALUE)
    ADD_DEFINITIONS(-DMENGINE_SECURE_VALUE="${MENGINE_SECURE_VALUE}")
endif()

if(COMMAND MENGINE_PREPARE_FUNCTION)
    MENGINE_PREPARE_FUNCTION()
endif()

if(MENGINE_XCODE_DEPLOY_PATH)
    if(EXISTS "${MENGINE_XCODE_DEPLOY_PATH}/mengine_prepare.cmake")
        include("${MENGINE_XCODE_DEPLOY_PATH}/mengine_prepare.cmake")
    endif()
endif()

INCLUDE_DIRECTORIES(${MENGINE_SOURCE_DIR})
INCLUDE_DIRECTORIES(${THIRDPARTY_DIR}/libmath/include)
INCLUDE_DIRECTORIES(${THIRDPARTY_DIR}/stdex/include)

SET(APPLICATION_LINK_LIBRARIES)
SET(APPLICATION_DEPENDENCIES)
SET(APPLICATION_STATIC_PLUGINS)
SET(APPLICATION_APPLE_FRAMEWORKS)
SET(APPLICATION_APPLE_FRAMEWORK_WITH_PATH)
SET(APPLICATION_APPLE_COCOAPODS)
SET(APPLICATION_APPLE_APPLICATION_DELEGATE)
SET(APPLICATION_MACOS_DYLIB)
SET(APPLICATION_MACOS_DYLIB_WITH_SIGN)