SET(CMAKE_TEMP_DIR ${CMAKE_BINARY_DIR}/solutions)

if(MENGINE_LOGGER_DEBUG)
    ADD_DEFINITIONS(-DMENGINE_LOGGER_DEBUG)
endif()

if(MENGINE_BUILD_MENGINE_MASTER_RELEASE)
    ADD_DEFINITIONS(-DMENGINE_MASTER_RELEASE)
endif()

if(MENGINE_USE_SCRIPT_SERVICE)
    ADD_DEFINITIONS(-DMENGINE_USE_SCRIPT_SERVICE)
endif()

if(MENGINE_ARCHITECTURE_X86)
    ADD_DEFINITIONS(-DMENGINE_ARCHITECTURE_X86)
endif()

if(MENGINE_ARCHITECTURE_X64)
    ADD_DEFINITIONS(-DMENGINE_ARCHITECTURE_X64)
endif()

INCLUDE_DIRECTORIES(${MENGINE_SOURCE_DIR})
INCLUDE_DIRECTORIES(${THIRDPARTY_DIR}/libmath/include)
INCLUDE_DIRECTORIES(${THIRDPARTY_DIR}/stdex/include)

SET(APPLICATION_DEPENDENCIES)
SET(APPLICATION_LINK_LIBRARIES)