SET(APPLICATION_LINK_LIBRARIES)
SET(APPLICATION_DEPENDENCIES)
SET(APPLICATION_STATIC_PLUGINS)
SET(APPLICATION_APPLE_FRAMEWORKS)
SET(APPLICATION_APPLE_FRAMEWORK_WITH_PATH)
SET(APPLICATION_APPLE_COCOAPODS)
SET(APPLICATION_APPLE_APPLICATION_DELEGATE)
SET(APPLICATION_APPLE_RESOURCES)
SET(APPLICATION_MACOS_DYLIB)
SET(APPLICATION_MACOS_DYLIB_WITH_SIGN)

SET(MENGINE_CONFIG_DEFINITIONS)

if(MENGINE_BUILD_MENGINE_MASTER_RELEASE)
    MENGINE_ADD_DEFINITION(MENGINE_MASTER_RELEASE)
endif()

if(MENGINE_BUILD_MENGINE_BUILD_PUBLISH)
    MENGINE_ADD_DEFINITION(MENGINE_BUILD_PUBLISH)
endif()

if(MENGINE_BUILD_MENGINE_LOGGER_LEVEL_FORCE_VERBOSE)
    MENGINE_ADD_DEFINITION(MENGINE_LOGGER_LEVEL_FORCE_VERBOSE=1)
endif()

if(MENGINE_BUILD_MENGINE_DEVELOPMENT)
    MENGINE_ADD_DEFINITION(MENGINE_BUILD_DEVELOPMENT)
endif()

if(MENGINE_USE_SCRIPT_SERVICE)
    MENGINE_ADD_DEFINITION(MENGINE_USE_SCRIPT_SERVICE)
endif()

if(MENGINE_SECURE_VALUE)
    MENGINE_ADD_DEFINITION(MENGINE_SECURE_VALUE="${MENGINE_SECURE_VALUE}")
endif()

if(COMMAND MENGINE_PREPARE_FUNCTION)
    MENGINE_PREPARE_FUNCTION()
endif()

if(MENGINE_ARCHITECTURE_X86)
    MENGINE_ADD_DEFINITION(MENGINE_ENVIRONMENT_ARCHITECTURE_X86)
elseif(MENGINE_ARCHITECTURE_X64)
    MENGINE_ADD_DEFINITION(MENGINE_ENVIRONMENT_ARCHITECTURE_X64)
endif()

if(MENGINE_WINDOWS_STORE)
    MENGINE_ADD_DEFINITION(MENGINE_WINDOWS_STORE)
endif()

set(MENGINE_BUILD_NUMBER "0" CACHE STRING "MENGINE_BUILD_NUMBER")
set(MENGINE_BUILD_VERSION "Versionless" CACHE STRING "MENGINE_BUILD_VERSION")

if(MENGINE_BUILD_NUMBER STREQUAL "AUTO")
    string(TIMESTAMP MENGINE_BUILD_NUMBER "%Y%m%d%H%M%S")
endif()
    
if(MENGINE_BUILD_VERSION STREQUAL "AUTO")
    string(TIMESTAMP MENGINE_BUILD_VERSION "%Y.%m.%d")
endif()

if(NOT MENGINE_BUILD_NUMBER MATCHES "^[0-9]+$")
    MESSAGE(FATAL_ERROR "Build number '${MENGINE_BUILD_NUMBER}' not valid INTEGER value")
endif()

IF(MENGINE_DEPLOY_PATH)
    IF(NOT EXISTS "${MENGINE_DEPLOY_PATH}")
        MESSAGE(FATAL_ERROR "Deploy path setup invalid path '${MENGINE_DEPLOY_PATH}'")
    ENDIF()
ENDIF()

SET(MENGINE_DEPLOY_PATH "" CACHE STRING "Mengine deploy path")

MESSAGE("MENGINE_DEPLOY_PATH: ${MENGINE_DEPLOY_PATH}")

if(MENGINE_DEPLOY_PATH)
    if(EXISTS "${MENGINE_DEPLOY_PATH}/mengine_prepare.cmake")
        include("${MENGINE_DEPLOY_PATH}/mengine_prepare.cmake")
    endif()
endif()

INCLUDE_DIRECTORIES(${MENGINE_SOURCE_DIR})
INCLUDE_DIRECTORIES(${THIRDPARTY_DIR}/libmath/include)
INCLUDE_DIRECTORIES(${THIRDPARTY_DIR}/stdex/include)