if(NOT DEFINED ENV{MINGW32_ROOT})
    message(FATAL_ERROR "Required ENV variable MINGW32_ROOT does not exists")
else()
    SET(MINGW32_ROOT $ENV{MINGW32_ROOT})
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

list(APPEND CMAKE_PREFIX_PATH
    ${MINGW32_ROOT}/i686-w64-mingw32
    ${MINGW32_ROOT}
)

SET(CMAKE_ASM_MASM_COMPILER    "uasm")
SET(CMAKE_C_COMPILER           "clang")
SET(CMAKE_CXX_COMPILER         "clang++")