set(CMAKE_CROSSCOMPILING TRUE)

if(NOT DEFINED ENV{MINGW64_ROOT})
    message(FATAL_ERROR "Required ENV variable MINGW64_ROOT does not exists")
else()
    SET(MINGW_ROOT $ENV{MINGW64_ROOT})
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

list(APPEND CMAKE_PREFIX_PATH
    ${MINGW_ROOT}
)

SET(CMAKE_ASM_MASM_COMPILER    "uasm")
SET(CMAKE_C_COMPILER           "clang")
SET(CMAKE_CXX_COMPILER         "clang++")