set(CMAKE_CROSSCOMPILING TRUE)

SET(CMAKE_SYSTEM_NAME "WindowsStore" CACHE STRING "CMAKE_SYSTEM_NAME" FORCE)
SET(CMAKE_SYSTEM_PROCESSOR "aarch64" CACHE STRING "CMAKE_SYSTEM_PROCESSOR" FORCE)
SET(CMAKE_SYSTEM_VERSION "10.0" CACHE STRING "CMAKE_SYSTEM_VERSION" FORCE)