MENGINE_PROJECT(MengineConverter)

ADD_FILTER(
src
    MengineConverter.cpp
    Convert.cpp
    Convert.h
)

INCLUDE_DIRECTORIES(${THIRDPARTY_CONFIG_DIR}/jansson/include)
INCLUDE_DIRECTORIES(${THIRDPARTY_DIR}/jansson/include)

ADD_MENGINE_TOOL_EXECUTABLE()

TARGET_LINK_LIBRARIES(${PROJECT_NAME} ToolEngine)
TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${THIRDPARTY_LIB_DIR}/${MENGINE_LIB_PREFIX}jansson${MENGINE_LIB_SUFFIX})
